# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Distant
site_url: https://distant.dev
repo_url: https://github.com/chipsenkbeil/distant
site_description: Libraries and tooling for working remotely
site_author: Chip Senkbeil
copyright: Chip Senkbeil © 2023

nav:
  - Home: 'index.md'
  - Getting Started:
    - Installation:
      - 'getting-started/installation/unix.md'
      - 'getting-started/installation/windows.md'
      - 'getting-started/installation/manually-download.md'
      - 'getting-started/installation/from-source.md'
    - 'getting-started/usage.md'
  - Reference:
    - CLI:
      - Config:
        - Config: 'reference/cli/config/index.md'
        - 'reference/cli/config/client.md'
        - 'reference/cli/config/generate.md'
        - 'reference/cli/config/manager.md'
        - 'reference/cli/config/server.md'
      - Commands:
        - Commands: 'reference/cli/commands/index.md'
        - 'reference/cli/commands/api.md'
        - 'reference/cli/commands/connect.md'
        - Filesystem:
          - 'reference/cli/commands/fs/copy.md'
          - 'reference/cli/commands/fs/exists.md'
          - 'reference/cli/commands/fs/make-dir.md'
          - 'reference/cli/commands/fs/metadata.md'
          - 'reference/cli/commands/fs/read.md'
          - 'reference/cli/commands/fs/remove.md'
          - 'reference/cli/commands/fs/rename.md'
          - 'reference/cli/commands/fs/search.md'
          - 'reference/cli/commands/fs/set-permissions.md'
          - 'reference/cli/commands/fs/watch.md'
          - 'reference/cli/commands/fs/write.md'
        - Generate:
          - 'reference/cli/commands/generate/completion.md'
          - 'reference/cli/commands/generate/config.md'
        - 'reference/cli/commands/launch.md'
        - Manager:
          - 'reference/cli/commands/manager/info.md'
          - 'reference/cli/commands/manager/kill.md'
          - 'reference/cli/commands/manager/list.md'
          - 'reference/cli/commands/manager/listen.md'
          - 'reference/cli/commands/manager/select.md'
          - 'reference/cli/commands/manager/service.md'
          - 'reference/cli/commands/manager/version.md'
        - Server:
          - 'reference/cli/commands/server/listen.md'
        - 'reference/cli/commands/shell.md'
        - 'reference/cli/commands/spawn.md'
        - 'reference/cli/commands/system-info.md'
        - 'reference/cli/commands/version.md'
      - Guides:
        - 'reference/cli/guides/spawning-the-manager.md'
      - JSON API:
        - JSON API: 'reference/cli/json-api/index.md'
        - 'reference/cli/json-api/authentication.md'
        - Messages:
          - Messages: 'reference/cli/json-api/messages/index.md'
          - 'reference/cli/json-api/messages/cancel_search.md'
          - 'reference/cli/json-api/messages/copy.md'
          - 'reference/cli/json-api/messages/dir_create.md'
          - 'reference/cli/json-api/messages/dir_read.md'
          - 'reference/cli/json-api/messages/exists.md'
          - 'reference/cli/json-api/messages/file_append.md'
          - 'reference/cli/json-api/messages/file_append_text.md'
          - 'reference/cli/json-api/messages/file_read.md'
          - 'reference/cli/json-api/messages/file_read_text.md'
          - 'reference/cli/json-api/messages/file_write.md'
          - 'reference/cli/json-api/messages/file_write_text.md'
          - 'reference/cli/json-api/messages/metadata.md'
          - 'reference/cli/json-api/messages/proc_kill.md'
          - 'reference/cli/json-api/messages/proc_resize_pty.md'
          - 'reference/cli/json-api/messages/proc_spawn.md'
          - 'reference/cli/json-api/messages/proc_stdin.md'
          - 'reference/cli/json-api/messages/remove.md'
          - 'reference/cli/json-api/messages/rename.md'
          - 'reference/cli/json-api/messages/search.md'
          - 'reference/cli/json-api/messages/set_permissions.md'
          - 'reference/cli/json-api/messages/system_info.md'
          - 'reference/cli/json-api/messages/unwatch.md'
          - 'reference/cli/json-api/messages/version.md'
          - 'reference/cli/json-api/messages/watch.md'
  - About:
    - 'about/overview.md'
    - 'about/features.md'
    - 'about/architecture.md'

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.svg
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.tabs
    - navigation.tracking
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - optimize
  - search
  - macros:
      module_name: macros
      on_error_fail: true
      on_undefined: strict

extra_css:
  - stylesheets/extra.css
  - stylesheets/asciinema-player.css

extra_javascript:
  - javascripts/asciinema-player.min.js
