# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Distant
site_url: https://distant.dev
repo_url: https://github.com/chipsenkbeil/distant
site_description: Libraries and tooling for working remotely
site_author: Chip Senkbeil
copyright: Chip Senkbeil © 2023

nav:
  - Home: 'index.md'
  - About:
    - 'about/overview.md'
    - 'about/features.md'
    - 'about/architecture.md'
  - Getting Started:
    - 'getting-started/installation.md'
  - Reference:
    - 'reference/examples.md'

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.svg
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
  palette:
    primary: custom

plugins:
  - search

extra_css:
  - stylesheets/extra.css
